# Generated by Django 3.0.5 on 2025-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
